# Generated by Django 4.2.1 on 2023-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='urltitle',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Default Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
